"""Explicit platform backend selection; unrelated corpus SQLite stays local.

SQL remains parameterised. Only placeholders and our schema's identity syntax
are adapted here; application-specific upserts/locking are explicit in callers.
"""
from __future__ import annotations

import os
from pathlib import Path
import re
import sqlite3


def postgres_config(path):
    # CLI/index jobs must select the same backend as systemd, even when their
    # shell did not export EnvironmentFile. Read only DB keys, never mutate env.
    from dotenv import dotenv_values
    local = dotenv_values(Path(__file__).resolve().parents[3] / '.env.local')
    def setting(key, default=''):
        return os.environ.get(key, local.get(key) or default)
    dsn = setting('ZZAIMY_DATABASE_URL')
    selected = Path(setting('ZZAIMY_PLATFORM_SQLITE_PATH', 'data/platform/platform.db'))
    if not dsn or Path(path).resolve() != selected.resolve():
        return None
    schema = setting('ZZAIMY_DATABASE_SCHEMA')
    if not re.fullmatch(r'aura_(?:app|test)_[a-z0-9_]{1,40}', schema):
        raise ValueError('An explicit aura_app_* or aura_test_* runtime schema is required')
    return dsn, schema


def placeholders(statement: str) -> str:
    """Convert qmarks outside SQL literals/comments, retaining literal ? and %."""
    parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*|/\*[\s\S]*?\*/)", statement)
    return ''.join(part.replace('%', '%%') if i % 2 else part.replace('%', '%%').replace('?', '%s')
                   for i, part in enumerate(parts))


class Row:
    def __init__(self, keys, values):
        self._keys, self._values = keys, values

    def keys(self):
        return self._keys

    def __getitem__(self, key):
        return self._values[self._keys.index(key)] if isinstance(key, str) else self._values[key]

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)


def _row_factory(cursor):
    keys = [c.name for c in cursor.description] if cursor.description else []
    return lambda values: Row(keys, values)


class Cursor:
    def __init__(self, cursor, lastrowid=None):
        self._cursor, self.lastrowid = cursor, lastrowid

    def __getattr__(self, key):
        return getattr(self._cursor, key)

    def __iter__(self):
        return iter(self._cursor)


_IDENTITY_TABLES = frozenset(('documents', 'reviews', 'chat_sessions', 'chat_messages',
    'projects', 'project_notes', 'doc_chunks', 'files', 'doc_assets', 'regulation_chunks',
    'entities', 'datasets', 'quality_reports', 'egress_requests', 'draft_history',
    'mask_events', 'chat_sources', 'chat_revisions', 'chunk_questions'))


class PostgresConnection:
    dialect = 'postgres'

    def __init__(self, dsn, schema, readonly=False):
        import psycopg
        from psycopg import sql
        self.raw = psycopg.connect(dsn, connect_timeout=10, autocommit=True, row_factory=_row_factory)
        try:
            if not self.raw.execute('SELECT 1 FROM pg_namespace WHERE nspname=%s', (schema,)).fetchone():
                raise ValueError('Runtime schema does not exist; provision and verify it first')
            self.raw.execute(sql.SQL('SET search_path TO {}, pg_catalog').format(sql.Identifier(schema)))
            self.raw.execute("SET lock_timeout = '10s'")
            self.raw.execute("SET statement_timeout = '60s'")
            if readonly:
                self.raw.execute('SET default_transaction_read_only = on')
            self.raw.autocommit = readonly
        except Exception:
            self.raw.close()
            raise

    def execute(self, statement, parameters=()):
        match = re.match(r'\s*INSERT\s+INTO\s+(\w+)', statement, re.I)
        identity = bool(match and match[1] in _IDENTITY_TABLES and not re.search(r'\bRETURNING\b', statement, re.I))
        if identity:
            statement = statement.rstrip().rstrip(';') + ' RETURNING id'
        cursor = self.raw.execute(placeholders(statement), parameters)
        row = cursor.fetchone() if identity else None
        return Cursor(cursor, row[0] if row else None)

    def executemany(self, statement, parameters):
        cursor = self.raw.cursor()
        cursor.executemany(placeholders(statement), parameters)
        return Cursor(cursor)

    def executescript(self, script):
        # Internal DDL only; no user-supplied scripts.
        script = re.sub(r'--[^\n]*', '', script)
        script = re.sub(r'INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT',
                        'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', script, flags=re.I)
        for statement in script.split(';'):
            if statement.strip():
                self.execute(statement)

    def __enter__(self):
        return self

    def __exit__(self, kind, value, traceback):
        try:
            self.raw.commit() if kind is None else self.raw.rollback()
        finally:
            self.close()

    def close(self):
        self.raw.close()

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()


def connect(path, *, readonly=False):
    config = postgres_config(path)
    if config:
        return PostgresConnection(*config, readonly=readonly)
    conn = sqlite3.connect(Path(path).resolve().as_uri() + '?mode=ro', uri=True, timeout=10) if readonly else sqlite3.connect(path, timeout=10)
    conn.row_factory = sqlite3.Row
    return conn


def table_names(conn):
    query = "SELECT tablename FROM pg_tables WHERE schemaname=current_schema()" if getattr(conn, 'dialect', '') == 'postgres' else "SELECT name FROM sqlite_master WHERE type='table'"
    return {row[0] for row in conn.execute(query)}


def column_names(conn, table):
    if getattr(conn, 'dialect', '') == 'postgres':
        return {row[0] for row in conn.execute('SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=?', (table,))}
    if not re.fullmatch(r'[a-z_]+', table):
        raise ValueError('Invalid internal table name')
    return {row[1] for row in conn.execute(f'PRAGMA table_info({table})')}


def lock_session(conn, session_id):
    if getattr(conn, 'dialect', '') == 'postgres':
        conn.execute('SELECT id FROM chat_sessions WHERE id=? FOR UPDATE', (session_id,)).fetchone()
    else:
        conn.execute('BEGIN IMMEDIATE')


def install_functions(conn):
    """Small explicit SQL compatibility functions, scoped to runtime schema.

    이미 있으면 다시 만들지 않는다 — 연결마다 CREATE OR REPLACE 를 보내면 동시에 연결한 프로세스끼리
    「tuple concurrently updated」로 실패한다(2026-10-03 운영 실측: 동기화 회차가 연결 단계에서 떨어짐)."""
    have = {r[0] for r in conn.raw.execute(
        "SELECT proname FROM pg_proc WHERE pronamespace = current_schema()::regnamespace"
        " AND proname IN ('instr', 'json_extract')").fetchall()}
    if {"instr", "json_extract"} <= have:
        return
    conn.raw.execute("""CREATE OR REPLACE FUNCTION instr(text, text) RETURNS integer
        LANGUAGE sql IMMUTABLE STRICT AS 'SELECT strpos($1, $2)'""")
    conn.raw.execute("""CREATE OR REPLACE FUNCTION json_extract(text, text) RETURNS text
        LANGUAGE sql IMMUTABLE STRICT AS $$SELECT $1::jsonb ->> substring($2 from 3)$$""")
